In [4]:
import yfinance as yf

In [5]:
# Create a ticker object for AAPL
ticker = yf.Ticker("AAPL")

# Get the current price
current_price = ticker.history().tail(1)['Close'].iloc[0]

# Print the current price
print("Current Price of AAPL:", current_price)

Current Price of AAPL: 187.98500061035156

In [10]:
ticker.history()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2023-06-12 00:00:00-04:00,181.270004,183.889999,180.970001,183.789993,54274900,0.0,0.0
2023-06-13 00:00:00-04:00,182.800003,184.149994,182.440002,183.309998,54929100,0.0,0.0
2023-06-14 00:00:00-04:00,183.369995,184.389999,182.020004,183.949997,57462900,0.0,0.0
2023-06-15 00:00:00-04:00,183.960007,186.520004,183.779999,186.009995,65433200,0.0,0.0
2023-06-16 00:00:00-04:00,186.729996,186.990005,184.270004,184.919998,101235600,0.0,0.0
2023-06-20 00:00:00-04:00,184.410004,186.100006,184.410004,185.009995,49799100,0.0,0.0
2023-06-21 00:00:00-04:00,184.899994,185.410004,182.589996,183.960007,49515700,0.0,0.0
2023-06-22 00:00:00-04:00,183.740005,187.050003,183.669998,187.000000,51245300,0.0,0.0
2023-06-23 00:00:00-04:00,185.550003,187.559998,185.009995,186.679993,53079300,0.0,0.0
2023-06-26 00:00:00-04:00,186.830002,188.050003,185.229996,185.270004,48088700,0.0,0.0
2023-06-27 00:00:00-04:00,185.889999,188.389999,185.669998,188.059998,50730800,0.0,0.0
2023-06-28 00:00:00-04:00,187.929993,189.899994,187.600006,189.250000,51216800,0.0,0.0
2023-06-29 00:00:00-04:00,189.080002,190.070007,188.940002,189.589996,46347300,0.0,0.0
2023-06-30 00:00:00-04:00,191.630005,194.479996,191.259995,193.970001,85069600,0.0,0.0
2023-07-03 00:00:00-04:00,193.779999,193.880005,191.759995,192.460007,31458200,0.0,0.0
2023-07-05 00:00:00-04:00,191.570007,192.979996,190.619995,191.330002,46920300,0.0,0.0
2023-07-06 00:00:00-04:00,189.839996,192.020004,189.199997,191.809998,45094300,0.0,0.0
2023-07-07 00:00:00-04:00,191.410004,192.669998,190.240005,190.679993,46778000,0.0,0.0
2023-07-10 00:00:00-04:00,189.259995,189.990005,187.149994,187.910004,13291674,0.0,0.0